universe = vanilla
executable = run_pp_plot.sh

transfer_input_files = run_H0_estimation_for_pp_plot.py
request_memory = 209370
request_cpus = 50

log = ./log_files/out.log
error = ./log_files/out_pp_$(cluster)_$$([$(Process)+$(index)]).err
output = ./log_files/out_pp_$(cluster)_$$([$(Process)+$(index)]).out


notification = never

index = 0
queue 1
# queue index from(
#     0,
#     1,
#     2,
#     3,
#     4
# )
